package ventanas;

import clases.enfermera;
import conexion_bada.Insert_enfermera;
import conexion_bada.Insert;
import java.awt.Color;
import java.util.Calendar;
import java.text.DateFormat;
import java.util.ArrayList;

public class agregar_enfermera extends javax.swing.JFrame {
    
    DateFormat df = DateFormat.getDateInstance();
    ArrayList<enfermera> lista_enfermera = new ArrayList();

    public agregar_enfermera() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_cedula_enfermera = new javax.swing.JTextField();
        text_PrimerNombre_enfermera = new javax.swing.JTextField();
        text_SegundoNombre_enfermera = new javax.swing.JTextField();
        text_PrimerApellido_enfermera = new javax.swing.JTextField();
        text_SegundoApellido_enfermera = new javax.swing.JTextField();
        Femenino_enfermera = new javax.swing.JRadioButton();
        Masculino_enfermera = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text_email_enfermera = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_celular_enfermera = new javax.swing.JTextField();
        Guardar_enfermera = new javax.swing.JButton();
        Regresar_enfermera = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        text_direccion_enfermera = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        combo_sangre_enfermera = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Fecha_Nacimiento_enfermera = new com.toedter.calendar.JDateChooser();
        spiner_experiencia_enfermera = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR ENFERMERA/O");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 153, 255));
        jLabel13.setText("Datos Personales");

        jLabel2.setText("Cedula:");

        jLabel3.setText("Primer Nombre:");

        jLabel4.setText("Segundo Nombre:");

        jLabel5.setText("Primer Apellido:");

        jLabel6.setText("Segundo Apellido:");

        text_cedula_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_cedula_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_cedula_enfermera.setText("Ingrese la cedula");
        text_cedula_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_cedula_enfermeraMousePressed(evt);
            }
        });
        text_cedula_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cedula_enfermeraActionPerformed(evt);
            }
        });

        text_PrimerNombre_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerNombre_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerNombre_enfermera.setText("Ingrese el Primer nombre");
        text_PrimerNombre_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerNombre_enfermeraMousePressed(evt);
            }
        });
        text_PrimerNombre_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PrimerNombre_enfermeraActionPerformed(evt);
            }
        });

        text_SegundoNombre_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoNombre_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoNombre_enfermera.setText("Ingrese el Segundo nombre");
        text_SegundoNombre_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoNombre_enfermeraMousePressed(evt);
            }
        });

        text_PrimerApellido_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerApellido_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerApellido_enfermera.setText("Ingrese el Primer apellido");
        text_PrimerApellido_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerApellido_enfermeraMousePressed(evt);
            }
        });

        text_SegundoApellido_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoApellido_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoApellido_enfermera.setText("Ingrese el Segundo apellido");
        text_SegundoApellido_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoApellido_enfermeraMousePressed(evt);
            }
        });
        text_SegundoApellido_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_SegundoApellido_enfermeraActionPerformed(evt);
            }
        });

        grupo_sexo.add(Femenino_enfermera);
        Femenino_enfermera.setText("F");

        grupo_sexo.add(Masculino_enfermera);
        Masculino_enfermera.setText("M");
        Masculino_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masculino_enfermeraActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo");

        jLabel9.setText("E-mail");

        text_email_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_email_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_enfermera.setText("Ingrese el E-mail");
        text_email_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_email_enfermeraMousePressed(evt);
            }
        });

        jLabel10.setText("Celular");

        text_celular_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_celular_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_celular_enfermera.setText("Ingrese el celular");
        text_celular_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_celular_enfermeraMousePressed(evt);
            }
        });

        Guardar_enfermera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Guardar_enfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar (1).png"))); // NOI18N
        Guardar_enfermera.setText("Guardar");
        Guardar_enfermera.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Guardar_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_enfermeraActionPerformed(evt);
            }
        });

        Regresar_enfermera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Regresar_enfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        Regresar_enfermera.setText("Regresar");
        Regresar_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_enfermeraActionPerformed(evt);
            }
        });

        jLabel11.setText("Años de experiencia");

        jLabel14.setText("Dirección:");

        text_direccion_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_direccion_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_direccion_enfermera.setText("Ingrese la dirección");
        text_direccion_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_direccion_enfermeraMousePressed(evt);
            }
        });
        text_direccion_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccion_enfermeraActionPerformed(evt);
            }
        });

        jLabel15.setText("Tipo de sangre");

        combo_sangre_enfermera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jLabel16.setText("Fecha de nacimiento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel10)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(text_celular_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(104, 104, 104)
                                                    .addComponent(text_email_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(45, 45, 45)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_sangre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Masculino_enfermera)
                                            .addGap(37, 37, 37)
                                            .addComponent(Femenino_enfermera))))
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_direccion_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(text_SegundoApellido_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(text_cedula_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(67, 67, 67))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(text_PrimerApellido_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(text_SegundoNombre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel8)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(Fecha_Nacimiento_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(31, 31, 31)
                                        .addComponent(text_PrimerNombre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSeparator7)
                                        .addGap(299, 299, 299)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spiner_experiencia_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Guardar_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(Regresar_enfermera)
                .addGap(123, 123, 123))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(text_cedula_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_PrimerNombre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_SegundoNombre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Fecha_Nacimiento_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(text_PrimerApellido_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Masculino_enfermera)
                                .addComponent(Femenino_enfermera)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(text_SegundoApellido_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(text_direccion_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(text_email_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(combo_sangre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(text_celular_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Regresar_enfermera)
                                    .addComponent(Guardar_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spiner_experiencia_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_cedula_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_cedula_enfermeraMousePressed
        
        text_cedula_enfermera.setText("");
        text_cedula_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_enfermeraMousePressed

    private void text_cedula_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cedula_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_enfermeraActionPerformed

    private void text_PrimerNombre_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerNombre_enfermeraMousePressed
        text_PrimerNombre_enfermera.setText("");
        text_PrimerNombre_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_enfermeraMousePressed

    private void text_PrimerNombre_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PrimerNombre_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_enfermeraActionPerformed

    private void text_SegundoNombre_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoNombre_enfermeraMousePressed
        text_SegundoNombre_enfermera.setText("");
        text_SegundoNombre_enfermera.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoNombre_enfermeraMousePressed

    private void text_PrimerApellido_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerApellido_enfermeraMousePressed
        text_PrimerApellido_enfermera.setText("");
        text_PrimerApellido_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerApellido_enfermeraMousePressed

    private void text_SegundoApellido_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoApellido_enfermeraMousePressed
        text_SegundoApellido_enfermera.setText("");
        text_SegundoApellido_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoApellido_enfermeraMousePressed

    private void text_SegundoApellido_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_SegundoApellido_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoApellido_enfermeraActionPerformed

    private void Masculino_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masculino_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Masculino_enfermeraActionPerformed

    private void text_email_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_email_enfermeraMousePressed
        text_email_enfermera.setText("");
        text_email_enfermera.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_email_enfermeraMousePressed

    private void text_celular_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_celular_enfermeraMousePressed
        text_celular_enfermera.setText("");
        text_celular_enfermera.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_celular_enfermeraMousePressed

    private void Guardar_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_enfermeraActionPerformed
        RegistrarEnfermera();
        limpiar();
    }//GEN-LAST:event_Guardar_enfermeraActionPerformed
    public void RegistrarEnfermera() {
        Insert_enfermera enfermera = new Insert_enfermera();
        String genero = "";
        //enfermera.setCodigo(text_codigo_enfermera.getText());
        enfermera.setCedula(text_cedula_enfermera.getText());
        enfermera.setPri_nomb(text_PrimerNombre_enfermera.getText());
        enfermera.setSeg_nombre(text_SegundoNombre_enfermera.getText());
        enfermera.setPrim_apell(text_PrimerApellido_enfermera.getText());
        enfermera.setSeg_apelli(text_SegundoApellido_enfermera.getText());
        if (Masculino_enfermera.isSelected()) {
            genero = "hombre";
        }
        if (Femenino_enfermera.isSelected()) {
            genero = "mujer";
        }
        
        enfermera.setGenero(genero);
        enfermera.setTelefono(text_celular_enfermera.getText());
        enfermera.setCorreo(text_email_enfermera.getText());
        enfermera.setDireccion(text_direccion_enfermera.getText());
        
        
        String dia = Integer.toString(Fecha_Nacimiento_enfermera.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(Fecha_Nacimiento_enfermera.getCalendar().get(Calendar.MONTH) + 1);
        String año = Integer.toString(Fecha_Nacimiento_enfermera.getCalendar().get(Calendar.YEAR));
        String FechaNacimiento = (dia + "-" + mes + "-" + año);
        //String FechaNacimiento = df.format(Fecha_Nacimiento_enfermera.getDate());
        enfermera.setFecha_Nacimiento(FechaNacimiento);
        
        enfermera.setTipo_sangre(combo_sangre_enfermera.getSelectedItem().toString());
        enfermera.setAño_ecperiencia(spiner_experiencia_enfermera.getValue().toString());
        
        if (enfermera.InsertarEnfermera()) {
            System.out.println("Conexion Exitosa");
        } else {
            System.out.println("Conexion Erronea");
        }
    }

    public void limpiar() {
        
        //text_codigo_enfermera.setText("");
        text_cedula_enfermera.setText("");
        text_PrimerNombre_enfermera.setText("");
        text_SegundoNombre_enfermera.setText("");
        text_PrimerApellido_enfermera.setText("");
        text_SegundoApellido_enfermera.setText("");
        grupo_sexo.clearSelection();
        text_direccion_enfermera.setText("");
        text_email_enfermera.setText("");
        text_celular_enfermera.setText("");
        combo_sangre_enfermera.setSelectedIndex(0);
        spiner_experiencia_enfermera.setValue(0);
        
    }
    private void Regresar_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_enfermeraActionPerformed
        this.dispose();
        new crud_enfermera().setVisible(true);
    }//GEN-LAST:event_Regresar_enfermeraActionPerformed

    private void text_direccion_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_direccion_enfermeraMousePressed
        text_direccion_enfermera.setText("");
        text_direccion_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccion_enfermeraMousePressed

    private void text_direccion_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccion_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccion_enfermeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar_enfermera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha_Nacimiento_enfermera;
    private javax.swing.JRadioButton Femenino_enfermera;
    private javax.swing.JButton Guardar_enfermera;
    private javax.swing.JRadioButton Masculino_enfermera;
    private javax.swing.JButton Regresar_enfermera;
    private javax.swing.JComboBox<String> combo_sangre_enfermera;
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSpinner spiner_experiencia_enfermera;
    private javax.swing.JTextField text_PrimerApellido_enfermera;
    private javax.swing.JTextField text_PrimerNombre_enfermera;
    private javax.swing.JTextField text_SegundoApellido_enfermera;
    private javax.swing.JTextField text_SegundoNombre_enfermera;
    private javax.swing.JTextField text_cedula_enfermera;
    private javax.swing.JTextField text_celular_enfermera;
    private javax.swing.JTextField text_direccion_enfermera;
    private javax.swing.JTextField text_email_enfermera;
    // End of variables declaration//GEN-END:variables
}
