package ventanas;

import clases.enfermera;
import conexion_bada.Insert_enfermera;
import conexion_bada.Insert;
import java.awt.Color;
import java.util.Calendar;
import java.text.DateFormat;
import java.util.ArrayList;

public class agregar_enfermera extends javax.swing.JFrame {
    
    DateFormat df = DateFormat.getDateInstance();
    ArrayList<enfermera> lista_enfermera = new ArrayList();

    public agregar_enfermera() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text_direccion_enfermera = new javax.swing.JTextField();
        text_SegundoApellido_enfermera = new javax.swing.JTextField();
        text_cedula_enfermera = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text_PrimerNombre_enfermera = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        spiner_experiencia_enfermera = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        text_SegundoNombre_enfermera = new javax.swing.JTextField();
        text_PrimerApellido_enfermera = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Guardar_enfermera = new javax.swing.JButton();
        Regresar_enfermera = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcodigo_enfermera = new javax.swing.JTextField();
        Fecha_Nacimiento_enfermera = new com.toedter.calendar.JDateChooser();
        Masculino_enfermera = new javax.swing.JRadioButton();
        Femenino_enfermera = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        combo_sangre_enfermera = new javax.swing.JComboBox<>();
        text_celular_enfermera = new javax.swing.JTextField();
        text_email_enfermera = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtusurio_enfermera = new javax.swing.JTextField();
        txtcontrasena_enfermera = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(240, 220, 144));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR ENFERMERA/O");

        text_direccion_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_direccion_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_direccion_enfermera.setText("Ingrese la dirección");
        text_direccion_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_direccion_enfermeraMousePressed(evt);
            }
        });
        text_direccion_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccion_enfermeraActionPerformed(evt);
            }
        });

        text_SegundoApellido_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoApellido_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoApellido_enfermera.setText("Ingrese el Segundo apellido");
        text_SegundoApellido_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoApellido_enfermeraMousePressed(evt);
            }
        });
        text_SegundoApellido_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_SegundoApellido_enfermeraActionPerformed(evt);
            }
        });

        text_cedula_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_cedula_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_cedula_enfermera.setText("Ingrese la cedula");
        text_cedula_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_cedula_enfermeraMousePressed(evt);
            }
        });
        text_cedula_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cedula_enfermeraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cedula:");

        text_PrimerNombre_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerNombre_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerNombre_enfermera.setText("Ingrese el Primer nombre");
        text_PrimerNombre_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerNombre_enfermeraMousePressed(evt);
            }
        });
        text_PrimerNombre_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PrimerNombre_enfermeraActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Años de Experiencia:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("Fecha de nacimiento:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Datos Personales");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Segundo Nombre:");

        text_SegundoNombre_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoNombre_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoNombre_enfermera.setText("Ingrese el Segundo nombre");
        text_SegundoNombre_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoNombre_enfermeraMousePressed(evt);
            }
        });

        text_PrimerApellido_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerApellido_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerApellido_enfermera.setText("Ingrese el Primer apellido");
        text_PrimerApellido_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerApellido_enfermeraMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Segundo Apellido:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Dirección:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("E-mail:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Celular:");

        Guardar_enfermera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Guardar_enfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar (1).png"))); // NOI18N
        Guardar_enfermera.setToolTipText("Guardar");
        Guardar_enfermera.setBorder(null);
        Guardar_enfermera.setOpaque(false);
        Guardar_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_enfermeraActionPerformed(evt);
            }
        });

        Regresar_enfermera.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Regresar_enfermera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        Regresar_enfermera.setToolTipText("Regresar");
        Regresar_enfermera.setBorder(null);
        Regresar_enfermera.setOpaque(false);
        Regresar_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_enfermeraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Codigo:");

        grupo_sexo.add(Masculino_enfermera);
        Masculino_enfermera.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Masculino_enfermera.setText("M");
        Masculino_enfermera.setOpaque(false);
        Masculino_enfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masculino_enfermeraActionPerformed(evt);
            }
        });

        grupo_sexo.add(Femenino_enfermera);
        Femenino_enfermera.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Femenino_enfermera.setText("F");
        Femenino_enfermera.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Tipo de Sangre:");

        combo_sangre_enfermera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        text_celular_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_celular_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_celular_enfermera.setText("Ingrese el celular");
        text_celular_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_celular_enfermeraMousePressed(evt);
            }
        });

        text_email_enfermera.setForeground(new java.awt.Color(102, 102, 102));
        text_email_enfermera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_enfermera.setText("Ingrese el E-mail");
        text_email_enfermera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_email_enfermeraMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Primer Apellido:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Primer Nombre:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREAR USUARIO");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("NUEVO USUARIO:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("NUEVA CONTRASEÑA:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Sexo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(Guardar_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(Regresar_enfermera))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_email_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_direccion_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_SegundoApellido_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_PrimerApellido_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_SegundoNombre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_PrimerNombre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_cedula_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(29, 29, 29)
                                .addComponent(txtcodigo_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(34, 34, 34)
                                .addComponent(text_celular_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(28, 28, 28)
                                .addComponent(spiner_experiencia_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(combo_sangre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(35, 35, 35)
                                .addComponent(Masculino_enfermera)
                                .addGap(35, 35, 35)
                                .addComponent(Femenino_enfermera)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtcontrasena_enfermera, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                    .addComponent(txtusurio_enfermera))
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(26, 26, 26)
                        .addComponent(Fecha_Nacimiento_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Guardar_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(txtcodigo_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(text_cedula_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel19)
                                            .addComponent(Masculino_enfermera)
                                            .addComponent(Femenino_enfermera))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(Fecha_Nacimiento_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel4))
                                            .addComponent(combo_sangre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(spiner_experiencia_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(text_PrimerNombre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)
                                        .addComponent(text_SegundoNombre_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_PrimerApellido_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(text_celular_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(text_SegundoApellido_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(text_direccion_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(text_email_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtusurio_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtcontrasena_enfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Regresar_enfermera)))
                        .addGap(13, 13, 13)))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_cedula_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_cedula_enfermeraMousePressed
        
        text_cedula_enfermera.setText("");
        text_cedula_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_enfermeraMousePressed

    private void text_cedula_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cedula_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_enfermeraActionPerformed

    private void text_PrimerNombre_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerNombre_enfermeraMousePressed
        text_PrimerNombre_enfermera.setText("");
        text_PrimerNombre_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_enfermeraMousePressed

    private void text_PrimerNombre_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PrimerNombre_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_enfermeraActionPerformed

    private void text_SegundoNombre_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoNombre_enfermeraMousePressed
        text_SegundoNombre_enfermera.setText("");
        text_SegundoNombre_enfermera.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoNombre_enfermeraMousePressed

    private void text_PrimerApellido_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerApellido_enfermeraMousePressed
        text_PrimerApellido_enfermera.setText("");
        text_PrimerApellido_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerApellido_enfermeraMousePressed

    private void text_SegundoApellido_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoApellido_enfermeraMousePressed
        text_SegundoApellido_enfermera.setText("");
        text_SegundoApellido_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoApellido_enfermeraMousePressed

    private void text_SegundoApellido_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_SegundoApellido_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoApellido_enfermeraActionPerformed

    private void Masculino_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masculino_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Masculino_enfermeraActionPerformed

    private void text_email_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_email_enfermeraMousePressed
        text_email_enfermera.setText("");
        text_email_enfermera.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_email_enfermeraMousePressed

    private void text_celular_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_celular_enfermeraMousePressed
        text_celular_enfermera.setText("");
        text_celular_enfermera.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_celular_enfermeraMousePressed

    private void Guardar_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_enfermeraActionPerformed
        RegistrarEnfermera();
        limpiar();
    }//GEN-LAST:event_Guardar_enfermeraActionPerformed
    public void RegistrarEnfermera() {
        Insert_enfermera enfermera = new Insert_enfermera();
        String genero = "";
        //enfermera.setCodigo(text_codigo_enfermera.getText());
        enfermera.setCedula(text_cedula_enfermera.getText());
        enfermera.setPri_nomb(text_PrimerNombre_enfermera.getText());
        enfermera.setSeg_nombre(text_SegundoNombre_enfermera.getText());
        enfermera.setPrim_apell(text_PrimerApellido_enfermera.getText());
        enfermera.setSeg_apelli(text_SegundoApellido_enfermera.getText());
        if (Masculino_enfermera.isSelected()) {
            genero = "hombre";
        }
        if (Femenino_enfermera.isSelected()) {
            genero = "mujer";
        }
        
        enfermera.setGenero(genero);
        enfermera.setTelefono(text_celular_enfermera.getText());
        enfermera.setCorreo(text_email_enfermera.getText());
        enfermera.setDireccion(text_direccion_enfermera.getText());
        
        
        String dia = Integer.toString(Fecha_Nacimiento_enfermera.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(Fecha_Nacimiento_enfermera.getCalendar().get(Calendar.MONTH) + 1);
        String año = Integer.toString(Fecha_Nacimiento_enfermera.getCalendar().get(Calendar.YEAR));
        String FechaNacimiento = (dia + "-" + mes + "-" + año);
        //String FechaNacimiento = df.format(Fecha_Nacimiento_enfermera.getDate());
        enfermera.setFecha_Nacimiento(FechaNacimiento);
        
        enfermera.setTipo_sangre(combo_sangre_enfermera.getSelectedItem().toString());
        enfermera.setAño_ecperiencia(spiner_experiencia_enfermera.getValue().toString());
        
        if (enfermera.InsertarEnfermera()) {
            System.out.println("Conexion Exitosa");
        } else {
            System.out.println("Conexion Erronea");
        }
    }

    public void limpiar() {
        
        //text_codigo_enfermera.setText("");
        text_cedula_enfermera.setText("");
        text_PrimerNombre_enfermera.setText("");
        text_SegundoNombre_enfermera.setText("");
        text_PrimerApellido_enfermera.setText("");
        text_SegundoApellido_enfermera.setText("");
        grupo_sexo.clearSelection();
        text_direccion_enfermera.setText("");
        text_email_enfermera.setText("");
        text_celular_enfermera.setText("");
        combo_sangre_enfermera.setSelectedIndex(0);
        spiner_experiencia_enfermera.setValue(0);
        
    }
    private void Regresar_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_enfermeraActionPerformed
        this.dispose();
        new crud_enfermera().setVisible(true);
    }//GEN-LAST:event_Regresar_enfermeraActionPerformed

    private void text_direccion_enfermeraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_direccion_enfermeraMousePressed
        text_direccion_enfermera.setText("");
        text_direccion_enfermera.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccion_enfermeraMousePressed

    private void text_direccion_enfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccion_enfermeraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccion_enfermeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregar_enfermera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha_Nacimiento_enfermera;
    private javax.swing.JRadioButton Femenino_enfermera;
    private javax.swing.JButton Guardar_enfermera;
    private javax.swing.JRadioButton Masculino_enfermera;
    private javax.swing.JButton Regresar_enfermera;
    private javax.swing.JComboBox<String> combo_sangre_enfermera;
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner spiner_experiencia_enfermera;
    private javax.swing.JTextField text_PrimerApellido_enfermera;
    private javax.swing.JTextField text_PrimerNombre_enfermera;
    private javax.swing.JTextField text_SegundoApellido_enfermera;
    private javax.swing.JTextField text_SegundoNombre_enfermera;
    private javax.swing.JTextField text_cedula_enfermera;
    private javax.swing.JTextField text_celular_enfermera;
    private javax.swing.JTextField text_direccion_enfermera;
    private javax.swing.JTextField text_email_enfermera;
    private javax.swing.JTextField txtcodigo_enfermera;
    private javax.swing.JTextField txtcontrasena_enfermera;
    private javax.swing.JTextField txtusurio_enfermera;
    // End of variables declaration//GEN-END:variables
}
