package ventanas;

import clases.paciente;
import ventanas.crud_paciente;
import conexion_bada.Conexion;
import conexion_bada.Insert;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import clases.validaciones;
import clases.persona;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
import java.util.Calendar;
import java.util.List;
//import java.util.List;
//import java.util.Locale;
//import javax.swing.table.DefaultTableModel;

public class Agregar_paciente extends javax.swing.JFrame {
    validaciones misvalidaciones = new validaciones();
    int id = 0;
    String Cedula = "";
    String Nombre = "";
    String Segundo_nombre = "";
    String Apellido = "";
    String Segundo_apellido = "";
    String Edad = "";
    String afiliacion = "";
    String genero = "";
    String fecha = "";
    String tipo_sangre = "";
    DateFormat df = DateFormat.getDateInstance();

    ArrayList<paciente> lista_Paciente = new ArrayList();
    Insert inser = new Insert();

    public Agregar_paciente() {
        initComponents();
        this.setLocationRelativeTo(null);
/////holaaaaaa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_cedula_paciente = new javax.swing.JTextField();
        text_PrimerNombre_paciente = new javax.swing.JTextField();
        text_SegundoNombre_paciente = new javax.swing.JTextField();
        text_PrimerApellido_paciente = new javax.swing.JTextField();
        text_SegundoApellido_paciente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Femenino_paciente = new javax.swing.JRadioButton();
        Masculino_paciente = new javax.swing.JRadioButton();
        Guardar_paciente = new javax.swing.JButton();
        Regresar_paciente = new javax.swing.JButton();
        check_iess = new javax.swing.JCheckBox();
        Checkbox_Seguro_paciente = new javax.swing.JLabel();
        fecha_Nacimiento_paciente = new com.toedter.calendar.JDateChooser();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        combo_sangre_paciente = new javax.swing.JComboBox<>();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        text_direccion_paciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        text_email_paciente = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        text_celular_paciente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fecha_ingreso_paciente = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        text_codigo_paciente = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        busc_codigo = new javax.swing.JTextField();
        buscar = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR PACIENTES");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 153, 255));
        jLabel13.setText("Datos Personales");

        jLabel2.setText("Cedula:");

        jLabel3.setText("Primer Nombre:");

        jLabel4.setText("Segundo Nombre:");

        jLabel5.setText("Primer Apellido:");

        jLabel6.setText("Segundo Apellido:");

        text_cedula_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_cedula_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_cedula_paciente.setText("Ingrese cedula");
        text_cedula_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_cedula_pacienteMousePressed(evt);
            }
        });
        text_cedula_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cedula_pacienteActionPerformed(evt);
            }
        });

        text_PrimerNombre_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerNombre_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerNombre_paciente.setText("Ingrese el Primer nombre");
        text_PrimerNombre_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerNombre_pacienteMousePressed(evt);
            }
        });
        text_PrimerNombre_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PrimerNombre_pacienteActionPerformed(evt);
            }
        });

        text_SegundoNombre_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoNombre_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoNombre_paciente.setText("Ingrese el Segundo nombre");
        text_SegundoNombre_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoNombre_pacienteMousePressed(evt);
            }
        });

        text_PrimerApellido_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerApellido_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerApellido_paciente.setText("Ingrese el Primer apellido");
        text_PrimerApellido_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerApellido_pacienteMousePressed(evt);
            }
        });

        text_SegundoApellido_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoApellido_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoApellido_paciente.setText("Ingrese el Segundo apellido");
        text_SegundoApellido_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoApellido_pacienteMousePressed(evt);
            }
        });
        text_SegundoApellido_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_SegundoApellido_pacienteActionPerformed(evt);
            }
        });

        jLabel18.setText("Fecha de nacimiento");

        jLabel8.setText("Sexo");

        grupo_sexo.add(Femenino_paciente);
        Femenino_paciente.setText("F");

        grupo_sexo.add(Masculino_paciente);
        Masculino_paciente.setText("M");
        Masculino_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masculino_pacienteActionPerformed(evt);
            }
        });

        Guardar_paciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Guardar_paciente.setText("Guardar");
        Guardar_paciente.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Guardar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_pacienteActionPerformed(evt);
            }
        });

        Regresar_paciente.setText("Regresar");
        Regresar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_pacienteActionPerformed(evt);
            }
        });

        Checkbox_Seguro_paciente.setText("Seguro");

        jLabel10.setText("Tipo de sangre");

        combo_sangre_paciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jLabel14.setText("Dirección:");

        text_direccion_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_direccion_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_direccion_paciente.setText("Ingrese la dirección");
        text_direccion_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_direccion_pacienteMousePressed(evt);
            }
        });
        text_direccion_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccion_pacienteActionPerformed(evt);
            }
        });

        jLabel11.setText("E-mail");

        text_email_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_email_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_paciente.setText("Ingrese el E-mail");
        text_email_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_email_pacienteMousePressed(evt);
            }
        });

        jLabel15.setText("Celular");

        text_celular_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_celular_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_celular_paciente.setText("Ingrese el celular");
        text_celular_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_celular_pacienteMousePressed(evt);
            }
        });

        jLabel19.setText("Fecha de ingreso");

        jLabel7.setText("Código:");

        text_codigo_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_codigo_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_codigo_paciente.setText("Código de paciente");
        text_codigo_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_codigo_pacienteMousePressed(evt);
            }
        });
        text_codigo_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_codigo_pacienteActionPerformed(evt);
            }
        });

        modificar.setText("modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        buscar.setText("buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                                .addGap(356, 356, 356))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(text_PrimerNombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(text_cedula_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(jLabel5)
                                                            .addGap(30, 30, 30))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(jLabel4)
                                                            .addGap(18, 18, 18))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(text_SegundoNombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(text_PrimerApellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(text_direccion_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel6)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(text_SegundoApellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(116, 116, 116)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(344, 344, 344)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Guardar_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(149, 149, 149)
                                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(text_codigo_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(393, 393, 393)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel15)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(text_celular_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addGap(41, 41, 41)
                                                                .addComponent(text_email_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fecha_Nacimiento_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel10)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(combo_sangre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(60, 60, 60)
                                                        .addComponent(Checkbox_Seguro_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(check_iess))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(Masculino_paciente)
                                                .addGap(18, 18, 18)
                                                .addComponent(Femenino_paciente))
                                            .addComponent(jLabel8))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(fecha_ingreso_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(67, 67, 67)
                                                                .addComponent(busc_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGap(6, 6, 6))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(modificar)
                                                        .addGap(57, 57, 57)))))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Regresar_paciente)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Regresar_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel13)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_cedula_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(text_codigo_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Masculino_paciente)
                            .addComponent(Femenino_paciente)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(text_PrimerNombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_SegundoNombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_PrimerApellido_paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_SegundoApellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(8, 8, 8)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(text_direccion_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha_Nacimiento_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fecha_ingreso_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_email_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(text_celular_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(combo_sangre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Checkbox_Seguro_paciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(check_iess))
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busc_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Guardar_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(modificar)))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_cedula_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_cedula_pacienteMousePressed

        text_cedula_paciente.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_pacienteMousePressed

    private void text_cedula_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cedula_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_pacienteActionPerformed

    private void text_PrimerNombre_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerNombre_pacienteMousePressed

        text_PrimerNombre_paciente.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_pacienteMousePressed

    private void text_PrimerNombre_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PrimerNombre_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_pacienteActionPerformed

    private void text_SegundoNombre_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoNombre_pacienteMousePressed

        text_SegundoNombre_paciente.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoNombre_pacienteMousePressed

    private void text_PrimerApellido_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerApellido_pacienteMousePressed

        text_PrimerApellido_paciente.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerApellido_pacienteMousePressed

    private void text_SegundoApellido_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoApellido_pacienteMousePressed

        text_SegundoApellido_paciente.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoApellido_pacienteMousePressed

    private void text_SegundoApellido_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_SegundoApellido_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoApellido_pacienteActionPerformed

    private void Masculino_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masculino_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Masculino_pacienteActionPerformed

    private void Guardar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_pacienteActionPerformed
        RegistrarPacientes();
        limpiar();

    }//GEN-LAST:event_Guardar_pacienteActionPerformed
    public void llenar_paciente() {

        for (int i = 0; i < inser.ListaPaciente().size(); i++) {

            List<paciente> com = inser.ListaPaciente();
            com.stream().forEach(p -> {
                text_codigo_paciente.setText(p.getCodigo().toString());
                text_cedula_paciente.setText(p.getCedula().toString());
                text_PrimerNombre_paciente.setText(p.getPri_nomb().toString());
                text_SegundoNombre_paciente.setText(p.getSeg_nombre().toString());
                text_PrimerApellido_paciente.setText(p.getPri_nomb().toString());
                text_SegundoApellido_paciente.setText(p.getSeg_apelli().toString());
                text_email_paciente.setText(p.getCorreo().toString());
                text_direccion_paciente.setText(p.getDireccion().toString());
                text_celular_paciente.setText(p.getTelefono().toString());

            });
        }

    }

    public void RegistrarPacientes() {
        Insert persona = new Insert();
        Insert paciente = new Insert();
//        paciente.setCodigo(text_codigo_paciente.getText());
        persona.setCedula(text_cedula_paciente.getText());
        persona.setPri_nomb(text_PrimerNombre_paciente.getText());
        persona.setSeg_nombre(text_SegundoNombre_paciente.getText());
        persona.setPrim_apell(text_PrimerApellido_paciente.getText());
        persona.setSeg_apelli(text_SegundoApellido_paciente.getText());

        if (Masculino_paciente.isSelected()) {
            genero = "hombre";
        }
        if (Femenino_paciente.isSelected()) {
            genero = "mujer";
        }
        persona.setGenero(genero);

        if (check_iess.isSelected()) {
            afiliacion = "si";
        } else {
            afiliacion = "no";
        }
        persona.setCorreo(text_email_paciente.getText());

        String dia = Integer.toString(fecha_Nacimiento_paciente.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(fecha_Nacimiento_paciente.getCalendar().get(Calendar.MONTH) + 1);
        String año = Integer.toString(fecha_Nacimiento_paciente.getCalendar().get(Calendar.YEAR));
        String FechaNacimiento = (dia + "-" + mes + "-" + año);
        persona.setFecha_Nacimiento(FechaNacimiento);

        persona.setDireccion(text_direccion_paciente.getText());
        persona.setTelefono(text_celular_paciente.getText());
        persona.setTipo_sangre(combo_sangre_paciente.getSelectedItem().toString());

        String diaI = Integer.toString(fecha_ingreso_paciente.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mesI = Integer.toString(fecha_ingreso_paciente.getCalendar().get(Calendar.MONTH) + 1);
        String añoI = Integer.toString(fecha_ingreso_paciente.getCalendar().get(Calendar.YEAR));
        String FechaDeIngreso = (diaI + "-" + mesI + "-" + añoI);

        //String FechaDeIngreso = df.format(fecha_ingreso_paciente.getDate());
        paciente.setFecha_de_ingreso(FechaDeIngreso);
        paciente.setSeguro(afiliacion);
        paciente.setCedula(text_cedula_paciente.getText());

        if (persona.InsertarPersona()&& paciente.InsertarPaciente()) {
            System.out.println("Conexion Exitosa");
        } else {
            System.out.println("Conexion Erronea");
        }
//        limpiar();

    }

//     public void cargarTabla() {
//        DefaultTableModel tb = (DefaultTableModel) tabla_paciente.getModel();
//        tb.setNumRows(0);
//        List<paciente> com = inser.ListaCamioneros();
//        com.stream().forEach(p -> {
//            String[] cami = {p.getDni(), p.getNombre(), p.getTelefono(), p.getDireccion(), String.valueOf(p.getSalario()), p.getPoblacion()};
//            tb.addRow(cami);
//        });
//    }
    public void limpiar() {
        text_codigo_paciente.setText("");
        text_cedula_paciente.setText("");
        text_PrimerNombre_paciente.setText("");
        text_SegundoNombre_paciente.setText("");
        text_PrimerApellido_paciente.setText("");
        text_SegundoApellido_paciente.setText("");
        grupo_sexo.clearSelection();
        text_direccion_paciente.setText("");
        text_email_paciente.setText("");
        text_celular_paciente.setText("");
        combo_sangre_paciente.setSelectedIndex(0);
        check_iess.setSelected(false);
        fecha_Nacimiento_paciente.setCalendar(null);
        fecha_ingreso_paciente.setCalendar(null);
    }

    public boolean validaciones() {
        boolean validado = true;
        if (text_cedula_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la cedula del paciente");
        } else {
            if (!misvalidaciones.validar_cedula(text_cedula_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Cedula incorrecta");
                validado = false;
            }
        }
//
        if (text_PrimerNombre_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del paciente");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_PrimerNombre_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Primer nombre incorrecto");
                validado = false;
            }
        }
        if (text_SegundoNombre_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del paciente");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_SegundoNombre_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Segundo nombre incorrecto");
                validado = false;
            }
        }
        if (text_PrimerApellido_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el apellido del paciente");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_PrimerApellido_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Primer apellido incorrecto");
                validado = false;
            }
        }
        if (text_SegundoApellido_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el apellido del paciente");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_SegundoApellido_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Segundo apellido incorrecto");
                validado = false;
            }
        }
        if (text_direccion_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la direccion del paciente");
        } else {
            if (!misvalidaciones.validarDireccion(text_direccion_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Direccion invalida");
                validado = false;
            }
        }
        if (text_celular_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el celular del paciente");
        } else {
            if (!misvalidaciones.validarTelefono(text_celular_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Celular invalido");
                validado = false;
            }
        }
        if (text_email_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el correo del paciente");
        } else {
            if (!misvalidaciones.validarCorreo(text_email_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Correo invalido");
                validado = false;
            }
        }
      
        if (combo_sangre_paciente.getSelectedIndex()==0) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de sangre");
        }
        System.out.println(fecha_Nacimiento_paciente.getCalendar().toString());
        if (fecha_Nacimiento_paciente.getCalendar().toString().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de nacimiento del paciente");
        }
        if (String.valueOf(fecha_ingreso_paciente.getCalendar()).isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de ingreso del paciente");
        }
        if (!Masculino_paciente.isSelected() && !Femenino_paciente.isSelected()) {
            validado = false;
            System.out.println("holsa");
            JOptionPane.showMessageDialog(this, "seleccione un genero");
        }

        return validado;
    }

    public boolean validar_duplicado() {
        boolean encontrado = false;
        if (!text_cedula_paciente.getText().isEmpty()) {
            for (int i = 0; i < lista_Paciente.size(); i++) {
                if (lista_Paciente.get(i).getCedula().equals(text_cedula_paciente.getText())) {
                    encontrado = true;
                }
            }
        } else {

        }
        return encontrado;
    }
    private void Regresar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_pacienteActionPerformed
        this.dispose();
        new crud_paciente().setVisible(true);
    }//GEN-LAST:event_Regresar_pacienteActionPerformed

    private void text_direccion_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_direccion_pacienteMousePressed

        text_direccion_paciente.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_direccion_pacienteMousePressed

    private void text_direccion_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccion_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccion_pacienteActionPerformed

    private void text_email_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_email_pacienteMousePressed

        text_email_paciente.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_email_pacienteMousePressed

    private void text_celular_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_celular_pacienteMousePressed

        text_celular_paciente.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_celular_pacienteMousePressed

    private void text_codigo_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_codigo_pacienteMousePressed

        text_codigo_paciente.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_codigo_pacienteMousePressed

    private void text_codigo_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_codigo_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_codigo_pacienteActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        
        List<paciente> com = inser.ListaPaciente();
            com.stream().forEach(p -> {
        if (busc_codigo.getText().equals(p.getCodigo())) {
            
                llenar_paciente();
            
            
        }
            });
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Checkbox_Seguro_paciente;
    private javax.swing.JRadioButton Femenino_paciente;
    private javax.swing.JButton Guardar_paciente;
    private javax.swing.JRadioButton Masculino_paciente;
    private javax.swing.JButton Regresar_paciente;
    private javax.swing.JTextField busc_codigo;
    private javax.swing.JToggleButton buscar;
    private javax.swing.JCheckBox check_iess;
    private javax.swing.JComboBox<String> combo_sangre_paciente;
    private com.toedter.calendar.JDateChooser fecha_Nacimiento_paciente;
    private com.toedter.calendar.JDateChooser fecha_ingreso_paciente;
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField text_PrimerApellido_paciente;
    private javax.swing.JTextField text_PrimerNombre_paciente;
    private javax.swing.JTextField text_SegundoApellido_paciente;
    private javax.swing.JTextField text_SegundoNombre_paciente;
    private javax.swing.JTextField text_cedula_paciente;
    private javax.swing.JTextField text_celular_paciente;
    private javax.swing.JTextField text_codigo_paciente;
    private javax.swing.JTextField text_direccion_paciente;
    private javax.swing.JTextField text_email_paciente;
    // End of variables declaration//GEN-END:variables
}
