package ventanas;

import clases.paciente;
import ventanas.crud_paciente;
import conexion_bada.Conexion;
import conexion_bada.Insert;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import clases.validaciones;
import clases.persona;
import java.sql.ResultSet;
//import java.sql.Connection;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
import java.util.Calendar;
import java.util.List;
//import java.util.List;
//import java.util.Locale;
//import javax.swing.table.DefaultTableModel;

public class Agregar_paciente extends javax.swing.JFrame {

    validaciones misvalidaciones = new validaciones();
    int id = 0;
    String Cedula = "";
    String Nombre = "";
    String Segundo_nombre = "";
    String Apellido = "";
    String Segundo_apellido = "";
    String Edad = "";
    String afiliacion = "";
    String genero = "";
    String fecha = "";
    String tipo_sangre = "";
    DateFormat df = DateFormat.getDateInstance();

    ArrayList<paciente> lista_Paciente = new ArrayList();
    Insert inser = new Insert();

    public Agregar_paciente() {
        initComponents();
        this.setLocationRelativeTo(null);
//        inser.ListaPaciente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_sexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        buscar = new javax.swing.JToggleButton();
        modificar = new javax.swing.JButton();
        text_codigo_paciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fecha_ingreso_paciente = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        text_celular_paciente = new javax.swing.JTextField();
        text_email_paciente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        text_direccion_paciente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        combo_sangre_paciente = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        fecha_Nacimiento_paciente = new com.toedter.calendar.JDateChooser();
        Femenino_paciente = new javax.swing.JRadioButton();
        Masculino_paciente = new javax.swing.JRadioButton();
        Guardar_paciente = new javax.swing.JButton();
        Regresar_paciente = new javax.swing.JButton();
        check_iess = new javax.swing.JCheckBox();
        Checkbox_Seguro_paciente = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        text_SegundoApellido_paciente = new javax.swing.JTextField();
        text_PrimerApellido_paciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        text_PrimerNombre_paciente = new javax.swing.JTextField();
        text_cedula_paciente = new javax.swing.JTextField();
        text_SegundoNombre_paciente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(240, 239, 180));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Celular:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Datos Personales");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar (1).png"))); // NOI18N
        buscar.setToolTipText("buscar");
        buscar.setBorder(null);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/editar-documento.png"))); // NOI18N
        modificar.setToolTipText("modificar");
        modificar.setBorder(null);
        modificar.setOpaque(false);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        text_codigo_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_codigo_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_codigo_paciente.setText("Código de paciente");
        text_codigo_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_codigo_pacienteMousePressed(evt);
            }
        });
        text_codigo_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_codigo_pacienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Código:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("Fecha de Ingreso:");

        text_celular_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_celular_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_celular_paciente.setText("Ingrese el celular");
        text_celular_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_celular_pacienteMousePressed(evt);
            }
        });

        text_email_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_email_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_email_paciente.setText("Ingrese el E-mail");
        text_email_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_email_pacienteMousePressed(evt);
            }
        });
        text_email_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_email_pacienteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("E-mail:");

        text_direccion_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_direccion_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_direccion_paciente.setText("Ingrese la dirección");
        text_direccion_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_direccion_pacienteMousePressed(evt);
            }
        });
        text_direccion_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_direccion_pacienteActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("Dirección:");

        combo_sangre_paciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Tipo de Sangre:");

        grupo_sexo.add(Femenino_paciente);
        Femenino_paciente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Femenino_paciente.setText("F");
        Femenino_paciente.setOpaque(false);

        grupo_sexo.add(Masculino_paciente);
        Masculino_paciente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Masculino_paciente.setText("M");
        Masculino_paciente.setOpaque(false);
        Masculino_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masculino_pacienteActionPerformed(evt);
            }
        });

        Guardar_paciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Guardar_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salvar (1).png"))); // NOI18N
        Guardar_paciente.setToolTipText("Guardar");
        Guardar_paciente.setBorder(null);
        Guardar_paciente.setOpaque(false);
        Guardar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_pacienteActionPerformed(evt);
            }
        });

        Regresar_paciente.setBackground(new java.awt.Color(204, 204, 204));
        Regresar_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N
        Regresar_paciente.setToolTipText("Regresar");
        Regresar_paciente.setBorder(null);
        Regresar_paciente.setFocusPainted(false);
        Regresar_paciente.setOpaque(false);
        Regresar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Regresar_pacienteActionPerformed(evt);
            }
        });

        check_iess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        check_iess.setBorder(null);
        check_iess.setOpaque(false);
        check_iess.setPreferredSize(new java.awt.Dimension(35, 35));

        Checkbox_Seguro_paciente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Checkbox_Seguro_paciente.setText("Seguro:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Sexo:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("Fecha de Nacimiento");

        text_SegundoApellido_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoApellido_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoApellido_paciente.setText("Ingrese el Segundo apellido");
        text_SegundoApellido_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoApellido_pacienteMousePressed(evt);
            }
        });
        text_SegundoApellido_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_SegundoApellido_pacienteActionPerformed(evt);
            }
        });

        text_PrimerApellido_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerApellido_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerApellido_paciente.setText("Ingrese el Primer apellido");
        text_PrimerApellido_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerApellido_pacienteMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Primer Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Cedula:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Primer Apellido:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR PACIENTES");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Segundo Apellido:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Segundo Nombre:");

        text_PrimerNombre_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_PrimerNombre_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_PrimerNombre_paciente.setText("Ingrese el Primer nombre");
        text_PrimerNombre_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_PrimerNombre_pacienteMousePressed(evt);
            }
        });
        text_PrimerNombre_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_PrimerNombre_pacienteActionPerformed(evt);
            }
        });

        text_cedula_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_cedula_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_cedula_paciente.setText("Ingrese cedula");
        text_cedula_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_cedula_pacienteMousePressed(evt);
            }
        });
        text_cedula_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_cedula_pacienteActionPerformed(evt);
            }
        });

        text_SegundoNombre_paciente.setForeground(new java.awt.Color(102, 102, 102));
        text_SegundoNombre_paciente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_SegundoNombre_paciente.setText("Ingrese el Segundo nombre");
        text_SegundoNombre_paciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                text_SegundoNombre_pacienteMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(344, 344, 344))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_PrimerNombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(text_cedula_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_PrimerApellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_direccion_paciente)
                                    .addComponent(text_celular_paciente)
                                    .addComponent(text_SegundoApellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Guardar_paciente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(text_SegundoNombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(36, 36, 36)
                                        .addComponent(text_codigo_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(Masculino_paciente))
                                            .addComponent(jLabel8)
                                            .addComponent(Checkbox_Seguro_paciente)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(check_iess, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(29, 29, 29)
                                        .addComponent(Femenino_paciente))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(32, 32, 32)
                                        .addComponent(combo_sangre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fecha_Nacimiento_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(34, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(27, 27, 27)
                                        .addComponent(fecha_ingreso_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Regresar_paciente)
                                            .addComponent(text_email_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(modificar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(text_codigo_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(text_cedula_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(text_PrimerNombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addComponent(fecha_ingreso_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Masculino_paciente)
                                .addComponent(Femenino_paciente))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(text_SegundoNombre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Checkbox_Seguro_paciente)
                                .addComponent(jLabel5))
                            .addComponent(check_iess, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(text_PrimerApellido_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(combo_sangre_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(text_SegundoApellido_paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_direccion_paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fecha_Nacimiento_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_email_paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_celular_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Guardar_paciente)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificar)
                    .addComponent(Regresar_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_cedula_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_cedula_pacienteMousePressed

        text_cedula_paciente.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_pacienteMousePressed

    private void text_cedula_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_cedula_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_cedula_pacienteActionPerformed

    private void text_PrimerNombre_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerNombre_pacienteMousePressed

        text_PrimerNombre_paciente.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_pacienteMousePressed

    private void text_PrimerNombre_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_PrimerNombre_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerNombre_pacienteActionPerformed

    private void text_SegundoNombre_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoNombre_pacienteMousePressed

        text_SegundoNombre_paciente.setForeground(Color.BLACK);
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoNombre_pacienteMousePressed

    private void text_PrimerApellido_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_PrimerApellido_pacienteMousePressed

        text_PrimerApellido_paciente.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_PrimerApellido_pacienteMousePressed

    private void text_SegundoApellido_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_SegundoApellido_pacienteMousePressed

        text_SegundoApellido_paciente.setForeground(Color.BLACK);

        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoApellido_pacienteMousePressed

    private void text_SegundoApellido_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_SegundoApellido_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_SegundoApellido_pacienteActionPerformed

    private void Masculino_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masculino_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Masculino_pacienteActionPerformed

    private void Guardar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_pacienteActionPerformed
        RegistrarPacientes();
    }//GEN-LAST:event_Guardar_pacienteActionPerformed
//    public void llenar_paciente() {
//
//        for (int i = 0; i < inser.ListaPaciente().size(); i++) {
//            System.out.println(inser.ListaPaciente().get(i).getCedula());
//            List<paciente> com = inser.ListaPaciente();
//            com.stream().forEach(p -> {
//                text_codigo_paciente.setText(p.getCodigo());
//                text_cedula_paciente.setText(p.getCedula());
//                text_PrimerNombre_paciente.setText(p.getPri_nomb().toString());
//                text_SegundoNombre_paciente.setText(p.getSeg_nombre().toString());
//                text_PrimerApellido_paciente.setText(p.getPri_nomb().toString());
//                text_SegundoApellido_paciente.setText(p.getSeg_apelli().toString());
//                text_email_paciente.setText(p.getCorreo().toString());
//                text_direccion_paciente.setText(p.getDireccion().toString());
//                text_celular_paciente.setText(p.getTelefono().toString());
//
//            });
//        }
//
//    }

    public void RegistrarPacientes() {
        Insert persona = new Insert();
        Insert paciente = new Insert();
        System.out.println("holaaaaaaaaaaa" + text_cedula_paciente.getText());
//        llenar_paciente();
//        inser.ListaPaciente();
        try {
            if (validaciones()) {
                if (inser.validarduplicado(text_cedula_paciente.getText())) {
                    persona.setCedula(text_cedula_paciente.getText());
                    persona.setPri_nomb(text_PrimerNombre_paciente.getText());
                    persona.setSeg_nombre(text_SegundoNombre_paciente.getText());
                    persona.setPrim_apell(text_PrimerApellido_paciente.getText());
                    persona.setSeg_apelli(text_SegundoApellido_paciente.getText());

                    if (Masculino_paciente.isSelected()) {
                        genero = "hombre";
                    }
                    if (Femenino_paciente.isSelected()) {
                        genero = "mujer";
                    }
                    persona.setGenero(genero);

                    if (check_iess.isSelected()) {
                        afiliacion = "si";
                    } else {
                        afiliacion = "no";
                    }
                    persona.setCorreo(text_email_paciente.getText());

                    String dia = Integer.toString(fecha_Nacimiento_paciente.getCalendar().get(Calendar.DAY_OF_MONTH));
                    String mes = Integer.toString(fecha_Nacimiento_paciente.getCalendar().get(Calendar.MONTH) + 1);
                    String año = Integer.toString(fecha_Nacimiento_paciente.getCalendar().get(Calendar.YEAR));
                    String FechaNacimiento = (dia + "-" + mes + "-" + año);
                    persona.setFecha_Nacimiento(FechaNacimiento);

                    persona.setDireccion(text_direccion_paciente.getText());
                    persona.setTelefono(text_celular_paciente.getText());
                    persona.setTipo_sangre(combo_sangre_paciente.getSelectedItem().toString());

                    String diaI = Integer.toString(fecha_ingreso_paciente.getCalendar().get(Calendar.DAY_OF_MONTH));
                    String mesI = Integer.toString(fecha_ingreso_paciente.getCalendar().get(Calendar.MONTH) + 1);
                    String añoI = Integer.toString(fecha_ingreso_paciente.getCalendar().get(Calendar.YEAR));
                    String FechaDeIngreso = (diaI + "-" + mesI + "-" + añoI);

                    //String FechaDeIngreso = df.format(fecha_ingreso_paciente.getDate());
                    paciente.setFecha_de_ingreso(FechaDeIngreso);
                    paciente.setSeguro(afiliacion);
                    paciente.setCedula(text_cedula_paciente.getText());

                    if (persona.InsertarPersona() && paciente.InsertarPaciente()) {
                        System.out.println("Conexion Exitosa");
                        limpiar();
                    } else {
                        System.out.println("Conexion Erronea");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "EL PACIENTE YA EXISTE EN LA BASE DE DATOS");
                    text_cedula_paciente.setText("");
                }

            }
        } catch (NullPointerException n) {

        }

    }

//     public void cargarTabla() {
//        DefaultTableModel tb = (DefaultTableModel) tabla_paciente.getModel();
//        tb.setNumRows(0);
//        List<paciente> com = inser.ListaCamioneros();
//        com.stream().forEach(p -> {
//            String[] cami = {p.getDni(), p.getNombre(), p.getTelefono(), p.getDireccion(), String.valueOf(p.getSalario()), p.getPoblacion()};
//            tb.addRow(cami);
//        });
//    }
    public void limpiar() {
        text_codigo_paciente.setText("");
        text_cedula_paciente.setText("");
        text_PrimerNombre_paciente.setText("");
        text_SegundoNombre_paciente.setText("");
        text_PrimerApellido_paciente.setText("");
        text_SegundoApellido_paciente.setText("");
        grupo_sexo.clearSelection();
        text_direccion_paciente.setText("");
        text_email_paciente.setText("");
        text_celular_paciente.setText("");
        combo_sangre_paciente.setSelectedIndex(0);
        check_iess.setSelected(false);
        fecha_Nacimiento_paciente.setCalendar(null);
        fecha_ingreso_paciente.setCalendar(null);
    }

    public boolean validaciones() {
        boolean validado = true;

        if (text_cedula_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la cedula del paciente");
        } else {
            if (!misvalidaciones.validar_cedula(text_cedula_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Cedula incorrecta");
                validado = false;
            }
        }
//
        if (text_PrimerNombre_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del paciente");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_PrimerNombre_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Primer nombre incorrecto");
                validado = false;
            }
        }
        if (text_SegundoNombre_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del paciente");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_SegundoNombre_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Segundo nombre incorrecto");
                validado = false;
            }
        }
        if (text_PrimerApellido_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el apellido del paciente");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_PrimerApellido_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Primer apellido incorrecto");
                validado = false;
            }
        }
        if (text_SegundoApellido_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el apellido del paciente");
        } else {
            if (!misvalidaciones.validar_nombre_apellido(text_SegundoApellido_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Segundo apellido incorrecto");
                validado = false;
            }
        }
        if (text_direccion_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la direccion del paciente");
        } else {
            if (!misvalidaciones.validarDireccion(text_direccion_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Direccion invalida");
                validado = false;
            }
        }
        if (text_celular_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el celular del paciente");
        } else {
            if (!misvalidaciones.validarTelefono(text_celular_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Celular invalido");
                validado = false;
            }
        }
        if (text_email_paciente.getText().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese el correo del paciente");
        } else {
            if (!misvalidaciones.validarCorreo(text_email_paciente.getText())) {
                JOptionPane.showMessageDialog(this, "Correo invalido");
                validado = false;
            }
        }

        if (combo_sangre_paciente.getSelectedIndex() == 0) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Seleccione el tipo de sangre");
        }
//        System.out.println(String.valueOf(fecha_Nacimiento_paciente.getCalendar()));
        if (fecha_Nacimiento_paciente.getCalendar().toString().isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de nacimiento del paciente");
        }
        if (String.valueOf(fecha_ingreso_paciente.getCalendar()).isEmpty()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de ingreso del paciente");
        }
        if (!Masculino_paciente.isSelected() && !Femenino_paciente.isSelected()) {
            validado = false;
            JOptionPane.showMessageDialog(this, "seleccione un genero");
        }

        return validado;
    }

//    public boolean validar_duplicado() {
//        boolean encontrado = false;
//        if (!text_cedula_paciente.getText().isEmpty()) {
//            for (int i = 0; i < lista_Paciente.size(); i++) {
//                if (lista_Paciente.get(i).getCedula().equals(text_cedula_paciente.getText())) {
//                    System.out.println(lista_Paciente.get(i).getCedula());
//                    encontrado = true;
//                }
//            }
//        } else {
//
//        }
//        return encontrado;
//    }
    private void Regresar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Regresar_pacienteActionPerformed
        this.dispose();
        new crud_paciente().setVisible(true);
    }//GEN-LAST:event_Regresar_pacienteActionPerformed

    private void text_direccion_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_direccion_pacienteMousePressed

        text_direccion_paciente.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_direccion_pacienteMousePressed

    private void text_direccion_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_direccion_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_direccion_pacienteActionPerformed

    private void text_email_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_email_pacienteMousePressed

        text_email_paciente.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_email_pacienteMousePressed

    private void text_celular_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_celular_pacienteMousePressed

        text_celular_paciente.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_celular_pacienteMousePressed

    private void text_codigo_pacienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_codigo_pacienteMousePressed

        text_codigo_paciente.setForeground(Color.BLACK);
    }//GEN-LAST:event_text_codigo_pacienteMousePressed

    private void text_codigo_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_codigo_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_codigo_pacienteActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed

    }//GEN-LAST:event_modificarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

    }//GEN-LAST:event_buscarActionPerformed

    private void text_email_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_email_pacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_email_pacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_paciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Checkbox_Seguro_paciente;
    private javax.swing.JRadioButton Femenino_paciente;
    private javax.swing.JButton Guardar_paciente;
    private javax.swing.JRadioButton Masculino_paciente;
    private javax.swing.JButton Regresar_paciente;
    private javax.swing.JToggleButton buscar;
    private javax.swing.JCheckBox check_iess;
    private javax.swing.JComboBox<String> combo_sangre_paciente;
    private com.toedter.calendar.JDateChooser fecha_Nacimiento_paciente;
    private com.toedter.calendar.JDateChooser fecha_ingreso_paciente;
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField text_PrimerApellido_paciente;
    private javax.swing.JTextField text_PrimerNombre_paciente;
    private javax.swing.JTextField text_SegundoApellido_paciente;
    private javax.swing.JTextField text_SegundoNombre_paciente;
    private javax.swing.JTextField text_cedula_paciente;
    private javax.swing.JTextField text_celular_paciente;
    private javax.swing.JTextField text_codigo_paciente;
    private javax.swing.JTextField text_direccion_paciente;
    private javax.swing.JTextField text_email_paciente;
    // End of variables declaration//GEN-END:variables
}
