/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import conexion_bada.Insert_enfermera;
import clases.enfermera;
import clases.paciente;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class crud_enfermera extends javax.swing.JFrame {

    Insert_enfermera inser = new Insert_enfermera();

    public crud_enfermera() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtAgregarEnfermera = new javax.swing.JButton();
        BtBuscarEnfermera = new javax.swing.JButton();
        text_buscar = new javax.swing.JTextField();
        BtModificarEnfermera = new javax.swing.JButton();
        BtEliminarEnfermera = new javax.swing.JButton();
        BtRegresarEnfermera = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEnfermera = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 204));
        jLabel2.setText("LISTA DE ENFERMERA/O");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        BtAgregarEnfermera.setText("AGREGAR ENFERMERA");
        BtAgregarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAgregarEnfermeraActionPerformed(evt);
            }
        });
        jPanel1.add(BtAgregarEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        BtBuscarEnfermera.setText("BUSCAR ENFERMERA");
        BtBuscarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtBuscarEnfermeraActionPerformed(evt);
            }
        });
        jPanel1.add(BtBuscarEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        text_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(text_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 130, -1));

        BtModificarEnfermera.setText("MODIFICAR ENFERMERA");
        jPanel1.add(BtModificarEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        BtEliminarEnfermera.setText("ELIMINAR ENFERMERA");
        jPanel1.add(BtEliminarEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        BtRegresarEnfermera.setText("REGRESAR");
        BtRegresarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegresarEnfermeraActionPerformed(evt);
            }
        });
        jPanel1.add(BtRegresarEnfermera, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        TablaEnfermera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cédula", "Primer nombre", "Segundo nombre", "Primer apellido", "Segundo apellido", "Sexo", "Tipo de sangre", "Dirección", "Fecha de nacimiento", "E-mail", "Celular", "Años de experiencia"
            }
        ));
        jScrollPane1.setViewportView(TablaEnfermera);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 980, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_buscarActionPerformed

    private void BtRegresarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegresarEnfermeraActionPerformed
        this.dispose();
        new inicio_frame().setVisible(true);
    }//GEN-LAST:event_BtRegresarEnfermeraActionPerformed

    private void BtAgregarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAgregarEnfermeraActionPerformed
        this.dispose();
        new agregar_enfermera().setVisible(true);
    }//GEN-LAST:event_BtAgregarEnfermeraActionPerformed

    private void BtBuscarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtBuscarEnfermeraActionPerformed
        buscar_enfermera();
    }//GEN-LAST:event_BtBuscarEnfermeraActionPerformed
    public void buscar_enfermera() {
        String cedula = text_buscar.getText();
        var pacientefiltro = new ArrayList<enfermera>();

        inser.ListaEnfermera().forEach((e) -> {
            if (e.getCedula().equals(cedula)) {
                pacientefiltro.add(e);
            }
        });
        String matriz[][] = new String[pacientefiltro.size()][14];
        for (int j = 0; j < pacientefiltro.size(); j++) {
            matriz[j][0] = pacientefiltro.get(j).getCodigo();
            matriz[j][1] = pacientefiltro.get(j).getCedula();
            matriz[j][2] = pacientefiltro.get(j).getPri_nomb();
            matriz[j][3] = pacientefiltro.get(j).getSeg_nombre();
            matriz[j][4] = pacientefiltro.get(j).getPrim_apell();
            matriz[j][5] = pacientefiltro.get(j).getSeg_apelli();
            matriz[j][6] = pacientefiltro.get(j).getCorreo();
            matriz[j][7] = pacientefiltro.get(j).getGenero();
            matriz[j][8] = pacientefiltro.get(j).getDireccion();
            matriz[j][9] = pacientefiltro.get(j).getTelefono();
            matriz[j][10] = pacientefiltro.get(j).getTipo_sangre();
            matriz[j][11] = pacientefiltro.get(j).getAnio_experiencia();
            matriz[j][12] = pacientefiltro.get(j).getFecha_Nacimiento();
            

        }
        TablaEnfermera.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "codigo", "Nombre", "segundo_nombre", "primer apellido", "segundo apellido", "correo", "genero", "direccion", "telefono", "tipo sangre", "seguro", "fecha nacimiento", "fecha ingreso"
                }
        ));
    }
    public void cargarTabla() {
        DefaultTableModel tb = (DefaultTableModel) TablaEnfermera.getModel();
        tb.setNumRows(0);
        List<enfermera> com = inser.ListaEnfermera();
        com.stream().forEach(p -> {
            String[] cami = {p.getCodigo(), p.getCedula(), p.getPri_nomb(), p.getSeg_nombre(), p.getPrim_apell(), p.getSeg_apelli(), p.getCorreo(), p.getGenero(), p.getDireccion(), p.getTelefono(), p.getTipo_sangre(), p.getAnio_experiencia(), p.getFecha_Nacimiento()};
            tb.addRow(cami);
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crud_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crud_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crud_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crud_enfermera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crud_enfermera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAgregarEnfermera;
    private javax.swing.JButton BtBuscarEnfermera;
    private javax.swing.JButton BtEliminarEnfermera;
    private javax.swing.JButton BtModificarEnfermera;
    private javax.swing.JButton BtRegresarEnfermera;
    private javax.swing.JTable TablaEnfermera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField text_buscar;
    // End of variables declaration//GEN-END:variables
}
